### PR TITLE
feat(plugin): remove references recursively

### PR DESCRIPTION
**Pull request by layershifter**
Hello, guys! I want hear your thoughts and find out if you are ready to accept merge changes.

## Problem

We need such plugin at [Semantic-UI-React](https://github.com/Semantic-Org/Semantic-UI-React) (Semantic-Org/Semantic-UI-React#1663) to remove `debug` from our builds. So I'm interested in active maintaining of it.

Your plugin looks awesome, but it don't removes **all** references of specified import.

#### fixture

```js
import foo from 'foo';

foo.bar();
const bar = foo.bar();
bar.baz();
```

#### expected

```js
import foo from 'foo';
```

#### actual

```js
import foo from 'foo';

const bar = foo.bar();
bar.baz();
```

------------------

## Proposed changes

My changes are breaking, so according to semver should be released as `1.0`. In fact, I don't like work references, but I don't see another way. With proposed changes it will can remove even this:

#### fixture

```js
import foo from 'foo'
import foobar from 'foobar'

const bar = foo.bar()
const baz = bar.baz
const qux = bar.qux()

bar.baz.qux()
baz.qux()
qux()
foobar.baz()
```

#### expected

```js
import foobar from 'foobar'

foobar.baz()
```

### API, new configuration

```json
{
  "plugins": [["filter-imports", {
    "keepImports": true,
    "imports": { "foo": [ "default" ] }
  }]]
}
```

When `keepImports=true` will be kept, it also defaults to `true`.

#### `keepImports=true`

```js
import foo from 'foo';
import bar from 'bar';
```

#### `keepImports=false`

```js
import bar from 'bar';
```

### Tools

Plugin will require:
- `lodash`
- `babel` to transpile plugin's code
- `prettier` and `eslint`

You can take a look to [`package.json`](https://github.com/layershifter/babel-plugin-transform-react-handled-props/blob/master/package.json) of my plugin.

----

I will be glad to receive feedback from you.

### CODE REVIEW

**Comment by mmun** [comment]
@layershifter 

This a no brainer and I'm a bit embarrassed I hadn't considered it! PR happily accepted.

Point of clarification, I would expect the __actual__ to be

```js
import foo from 'foo';

bar.baz();
```

which is obviously terrible. No?

**Comment by layershifter** [comment]
@mmun No, I've update initial problem fixture. The current version of plugin removes only `ExpressionStatement`, while `const bar = foo.bar();` is `VariableDeclarator`.

**Comment by mmun** [comment]
Re: new configuration. I'm happy to make `keepImports: false` the default as it is what you usually want. Modules with side-effects are not super common _[citation needed]_.

Re: tools. That's all fine. We can also consider you adopting this module as I don't think it's used in ember-cli anymore.

**Comment by layershifter** [comment]
@mmun Thanks for suggestions :+1: I will continue to work on this PR.

**Comment by layershifter** [comment]
Ready for review :+1:

**Comment by mmun** [comment]
@layershifter Looks great, but the style does not match the ember-cli project.

Would you be prepared to adopt this repo and npm package? If so I'll confirm that this is OK with the team.

**Comment by layershifter** [comment]
> Looks great, but the style does not match the ember-cli project.

We can remove `prettier` and use eslint config from [ember-cli](https://github.com/ember-cli/ember-cli/blob/master/.eslintrc.js).

> Would you be prepared to adopt this repo and npm package? If so I'll confirm that this is OK with the team and make the transfers.

As I [see](https://www.npmjs.com/package/babel-plugin-filter-imports) it's used in `ember-*` packages. I think it will be better to leave it there and add me as collaborator. However, I'm ready to maintain this package.

**Comment by mmun** [comment]
@layershifter Ok, let's keep your PR as is and leave it in ember-cli for the time being (e.g. until the new 1.* gains some traction).

**Comment by mmun** [comment]
I've added you as a collaborator on this repo and an owner on npm (layershifter).

Please feel free to bump and publish a new major version when you see fit.

**Comment by layershifter** [comment]
@mmun Thanks for the cooperation :+1: I'm tested new version with my team, I'll push more changes soon.

**Pull request merged**
