### PR TITLE
chore(package): update to Babel 7

### PR DESCRIPTION
**Pull request by layershifter**
# Babel 7 Released

https://babeljs.io/blog/2018/08/27/7.0.0

---

It's time to go away from beta :+1: 

---

Replaces: #40, #41, #42.

### CODE REVIEW

**Comment by layershifter** [comment]
@mmun it seems that I was kicked from this org and now I don't have permissions to merge & release. Can you please merge it and ship `2.0.1`?

**Comment by mmun** [comment]
@layershifter Sorry about that. I don't know why that happened. I've re-granted you with admin rights. Feel free to transfer ownership if you'd prefer.

**Comment by kisenka** [comment]
@layershifter could you please merge it and make a release? 🙏

**Comment by layershifter** [comment]
Yes, I will do this on Friday. Currently, in the business trip :bus:

**Comment by layershifter** [comment]
@kisenka finally release in `2.0.2` :+1:

**Pull request merged**
